---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
ota:
  - platform: esphome
    encryption:
      key: !secret esphome_api_encryptionKey
