---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Lisbon"

  interfaces_time_api_package: !include ../interfaces/time/apiTime.yaml
  interfaces_time_mqtt_package: !include ../interfaces/time/mqttTime.yaml

packages:
  - ${ interfaces_enabled_api and interfaces_time_api_package or interfaces_time_mqtt_package }

globals:
  - {
      id: daily_reset,
      type: bool,
      restore_value: false,
      initial_value: "false",
    }
sensor:
  - <<: !include ../sensors/uptime.yaml