---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret wifi_iot_ssid
  wifi_password: !secret wifi_iot_password
  wifi_ap_password: "esphome-${slug}"

wifi:
  id: component_wifi
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  reboot_timeout: 10min
  manual_ip:
    static_ip: "${static_ip}"
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "${name}"
    password: "${wifi_ap_password}"

sensor:
  - <<: !include ../../sensors/wifi_signal_percentage.yaml
  - <<: !include ../../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../../sensors/text_sensors/wifi_info.yaml
