---
# Sensors are a basic integration in Home Assistant. They monitor the states and
# conditions of a variety of entities
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor: !include_dir_merge_list ../entities/sensors