---
# The file contains passwords and API tokens which need to be redacted if you want to share your configuration.
#
# https://www.home-assistant.io/docs/configuration/secrets/
#

# Google calendar configuration.yaml entry
google_client_id_calendar:
google_client_secret_calendar:

# Google assistant
google_assistant_private_key: ""

# wifi
wifi_iot_ssid: ''
wifi_iot_password: ''

# mqtt
mqtt_broker: ''
mqtt_username: ''
mqtt_password: ''

# whatsapp
whatsapp_phone: 
whatsapp_apikey: 

# Zigbee2mqtt
network_key: ''

# wunderground
wunderground_api_key: 
wunderground_my_pws_id: 


# ESPHome (generic)
esphome_ota_password: ''
esphome_api_password: ''
esphome_api_encryptionKey: ''
esphome_web_server_password: ''

# Nginx Proxy Manager
nginx_username: 
nginx_password: 

# HTTP component settings
http_trusted_proxies: ["","",""]

# Recorder
recorder_db_url: ""

# Influxdb
influxdb_username: ''
influxdb_password: ''

# Camera
camera_username: ''
camera_password: ''

# Telegram_bot
telegram_bot_api_key: ''
telegram_bot_allowed_chat_ids: [""]