# Google calendar
google_client_id_calendar: 
google_client_secret_calendar: 

# Google assistant
google_assistant_private_key: ""

# wifi
wifi_iot_ssid: '' 
wifi_iot_password: '' 

# mqtt
mqtt_broker: '' 
mqtt_user: '' 
mqtt_pass: '' 

# whatsapp
whatsapp_phone: 
whatsapp_apikey: 

# Zigbee2mqtt
network_key: 

# wunderground
wunderground_api_key: 
wunderground_my_pws_id: 


# ESPHome (generic)
espHome_ota: '' 
espHome_api_password: '' 
espHome_api_encryptionKey: ''
esphome_web_server_password: ''  

# Nginx Proxy Manager
nginx_username: 
nginx_password: 

# HTTP component settings
http_trusted_proxies: [""]

# Recorder
recorder_db_url: ""

# Influxdb
influxdb_username: ''
influxdb_password: ''