---
# Ethernet component package
#
# Contains my common Ethernet setup.
#
# https://esphome.io/components/ethernet.html
#
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip:
    static_ip: "${static_ip}"
    gateway: 10.0.0.1
    subnet: 255.255.255.0