sensor:
  - name: "Current Energy Price"
    unique_id: current_energy_price
    unit_of_measurement: "EUR/kWh"
    state: >
      {% set hora = now().hour | int %}
      {% if hora >= 22 or hora < 8 %}
        0.1291
      {% else %}
        0.2096
      {% endif %}
    availability: "true"
