sensor:
  - name: "Energy Price Hours"
    unique_id: energy_price_hours
    state: >
      {% set low_start = 22 %}
      {% set low_end = 8 %}
      {% set hora = now().hour %}
      {% set low = hora >= low_start or hora < low_end %}
      {% if low %}lowPrice{% else %}highPrice{% endif %}
    availability: "{{ now() is not none }}"
    attributes:
      start_time: >
        {% set low_start = 22 %}
        {% set low_end = 8 %}
        {% set hora = now().hour %}
        {% if hora >= low_start or hora < low_end %}{{ "%02d:00"|format(low_start) }}{% else %}{{ "%02d:00"|format(low_end) }}{% endif %}
      end_time: >
        {% set low_start = 22 %}
        {% set low_end = 8 %}
        {% set hora = now().hour %}
        {% if hora >= low_start or hora < low_end %}{{ "%02d:00"|format(low_end) }}{% else %}{{ "%02d:00"|format(low_start) }}{% endif %}
