sensor:
  - name: "Energy Price Hours"
    unique_id: energy_price_hours
    state: >
      {% set hora = now().hour %}
      {% if hora >= 22 or hora < 8 %}
        lowPrice
      {% else %}
        highPrice
      {% endif %}
    availability: "{{ now() is not none }}"
    attributes:
      start_time: >
        {% if now().hour >= 22 or now().hour < 8 %}
          "22:00"
        {% else %}
          "08:00"
        {% endif %}
      end_time: >
        {% if now().hour >= 22 or now().hour < 8 %}
          "08:00"
        {% else %}
          "22:00"
        {% endif %}
