
sensor:
  - name: "Current Energy Price €/kWh"
    unique_id: current_energy_price_eur_kwh
    unit_of_measurement: "€/kWh"
    state: >
      {% set period = states('sensor.energy_price_hours') %}
      {% if period == 'lowPrice' %}
        0.1162
      {% else %}
        0.1861
      {% endif %}
  - name: "Actual Sell Energy Price €/kWh"
    unique_id: actual_sell_energy_price_eur_kwh
    unit_of_measurement: "€/kWh"
    state: "0.04"
  - name: "Electricity Dynamic Price €/kWh"
    unique_id: electricity_dynamic_price_eur_kwh
    unit_of_measurement: "€/kWh"
    state: >
      {{ (states('sensor.omie_spot_price_pt') | float(0) * 0.001) | round(5) }}
  - name: "G9 Dynamic Tariff €/kWh"
    unique_id: g9_dynamic_tariff_eur_kwh
    unit_of_measurement: "€/kWh"
    state: >
      {% set omie = states('sensor.electricity_dynamic_price_eur_kwh') | float(0) %}
      {% set fadeq = 1.02 %}
      {% set losses = 0.02 %}
      {% set ggs = 0.0015 %}
      {% set mc = 0.001 %}
      {{ (omie * fadeq * (1 + losses) + ggs + mc) | round(5) }}
  - name: "G9 Tariff Difference €/kWh"
    unique_id: g9_tariff_difference_eur_kwh
    unit_of_measurement: "€/kWh"
    state: >
      {% set g9 = states('sensor.g9_dynamic_tariff_eur_kwh') | float(None) %}
      {% set current = states('sensor.current_energy_price_eur_kwh') | float(None) %}
      {% if g9 is not none and current is not none %}
        {{ (current - g9) | round(5) }}
      {% else %}
        unknown
      {% endif %}
