time:
  - <<: !include ../../sensors/time/homeassistant.yaml
    timezone: "${time_timezone}"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - <<: !include ../../sensors/time/sntp.yaml
    timezone: "${time_timezone}"

sensor:
  - <<: !include ../../sensors/uptime_timestamp.yaml