id: '1660602309138'
alias: 'motion sensor by snake'
description: ''
trigger:
- platform: event
  event_type: telegram_callback
  event_data:
    command: /repeat
- platform: state
  entity_id:
  - binary_sensor.snake_camara_motion
condition: []
action:
- service : script.notify_telegram_with_photo
  data_template : 
     i_file_name : "snake_{{now().strftime('%Y_%m_%d_%H_%M_%S_%f')}}.jpg"
mode: single