---
# The Climate integration allows you to control and monitor HVAC (heating, ventilating,
# and air conditioning) devices and thermostats.
#
# https://www.home-assistant.io/integrations/climate/
#
- platform: generic_thermostat
  name: gas heater
  heater: switch.heater
  target_sensor: sensor.kitchen_temperature
  min_temp: 15
  max_temp: 21
  ac_mode: false
  target_temp: 16
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1