substitutions:
  slug: bedroom
  name: bedroom
  description: The sensor of SensorBedroom!
  wifi_static_ip: 192.168.1.51

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_d1_mini.yaml

sensor:
  - <<: !include sensors/dht.yaml
    pin: D2
    model: DHT22

deep_sleep:
  run_duration: 20s
  sleep_duration: 1min