substitutions:
  slug: kitchen
  name: kitchen
  description: Control of kitchen!
  wifi_static_ip: 192.168.1.52

packages:
  <<: !include_dir_named components/common
  <<: !include_dir_named components/mqtt
  board: !include components/boards/wemos_d1_mini.yaml

switch:
  - platform: gpio
    name: ${name} boiler
    restore_mode: ALWAYS_OFF
    pin: D2

sensor:
  - <<: !include sensors/dht.yaml
    pin: D3
    model: DHT22

deep_sleep:
  run_duration: 20s
  sleep_duration: 2min