substitutions:
  slug: mailbox
  name: mailbox
  description: The sensor of mailbox!
  wifi_static_ip: 192.168.1.53

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_d1_mini.yaml

switch:
  - platform: gpio
    id: reset
    restore_mode: ALWAYS_OFF
    pin: D4
    inverted: true

binary_sensor:
  - platform: gpio
    id: button
    name: ${name} button
    pin:
      number: D8
      mode: INPUT_PULLUP
    
deep_sleep:
  id: deep_sleep_1
  #run_duration: 10s
  #sleep_duration: 4min