substitutions:
  label: esp1
  slug: sala
  name: sala
  description: The sensor of sala!
  board: ../boards/esp_wrover_kit.yaml

packages:
  <<: !include_dir_named common
  board: !include boards/esp_wrover_kit.yaml

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass
  birth_message:
    topic: ${name}/status
    payload: 'online'
  will_message:
    topic: ${name}/status
    payload: 'offline'
  on_message:
    - topic: ${name}/ota_mode
      payload: 'on'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: ${name}/ota_mode
      payload: 'off'
      then:
        - deep_sleep.enter: deep_sleep_1


sensor:
  - platform: dht
    pin: 15
    model: AM2302
    temperature:
      name: ${name} Temperature
    humidity:
      name: ${name} Humidity
    update_interval: 10s
  - platform: adc
    pin: 33
    name: ${name} Illuminance
    update_interval: 3s
    
deep_sleep:
  id: deep_sleep_1
  #run_duration: 40s
  #sleep_duration: 4min
  wakeup_pin:
    number: GPIO32
    inverted: True
    mode: INPUT_PULLUP
  wakeup_pin_mode: KEEP_AWAKE