
substitutions:
  display_name: sala1


esphome:
  name: ${display_name}
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: 192.168.1.51
    gateway: 192.168.1.1
    subnet: 255.255.255.0

 
captive_portal:

# Enable logging../../automations
logger:

# Enable Home Assistant API
api:
  password: "rui"

ota:
  password: !secret ESPHOME_ota

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass
  birth_message:
    topic: ${display_name}/STATUS
    payload: 'ON'
  will_message:
    topic: ${display_name}/STATUS
    payload: 'OFF'
  on_message:
    - topic: ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: ${display_name}/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1


i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.print("Hello World!");

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: ${display_name} button
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double"
          - mqtt.publish:
              topic: ${display_name}/binary_sensor/${display_name}_button/STATE
              payload: "Double"
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single_Long"
          - mqtt.publish:
              topic: ${display_name}/binary_sensor/${display_name}_button/STATE
              payload: "Single_Long"
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single_Short"
          - mqtt.publish:
              topic: ${display_name}/binary_sensor/${display_name}_button/STATE
              payload: "Single_Short"
  
      
sensor:
  - platform: dht
    pin: 15
    model: AM2302
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 30min
  - platform: adc
    pin: 33
    name: "Illuminance"
    update_interval: 5s

switch:
  - platform: gpio
    name: ${display_name}_rele
    pin: GPIO27
    inverted: True
    id: rele
    
output:
  - platform: ledc
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    id: status_led
    name: "Sonoff"
    output: blue_led    
    

deep_sleep:
  id: deep_sleep_1
  run_duration: 40s
  sleep_duration: 4min
  wakeup_pin:
    number: GPIO32
    inverted: True
    mode: INPUT_PULLUP
  wakeup_pin_mode: KEEP_AWAKE