substitutions:
  slug: watterpomptest
  name: watterpomptest
  description: Control of watterpomptest!
  wireguard_address: 10.10.10.3

packages:
  wifi_config: !include wifi_connection/wireguard.yaml
  board: !include boards/wemos_d1_mini.yaml
  <<: !include_dir_named common

api:
  password: !secret esphome_api_password
  #port: 9999

time:
  - platform: sntp
    id: my_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org


